### ISSUE TITLE
As a researcher I need to have basic sample information on the Tissue Viewer so that I can feel oriented and know something about the active sample.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#153]
Ensure the researcher has basic metadata about the active sample so they feel oriented and know something about the active sample by:

- [ ] Providing information below the Close Bar on the TV that includes the organ name, sex, age, and bmi. UX NOTE: Not all information may be available to show.

**Comment by bherr2** [comment]
@lecross I think we talked about this, the top nav bar takes this state rather than having two info lines (one for filter and one for sample) on the screen. Ref: https://xd.adobe.com/view/87cdc0cf-77ca-4c15-74a0-3db0b0e2f6af-f1fc/screen/79d2c16b-6f9a-48c8-af75-45bc95e22f14/5a-Detail-result-selection-136

**Comment by lecross** [comment]
Bruce, I think you are asking about the filter state info next to the Info Icon in the Logo Bar. That text reflects the currently applied fiters: Sex, Age, BMI. It is meant to provide an informational reference so that the user knows something about the overall data they are reviewing. Not a perfect solution, but that is the intention. That information does not have anything to do with an individual sample.


There looks to be an error in the image you sent. The information relevant to the sample is missing. Note the redline below. If that section is missing from the documentation, that is my fuck-up. I'll go back and review after sending this, updating the prototype and spec if this is missing.


Let me know if I have misinterpreted your question.



[cid:ba2d758c-6e28-468d-92cb-bf268136f17b]

________________________________

**Comment by lecross** [comment]
Bruce,


I reviewed the issue on my end. The spec doc looks correct. What didn't happen was an oversight by me. I did not push the latest version of the prototype live. Thus, there is the discrepancy. I have now pushed the correct version live.


https://xd.adobe.com/view/2760ad3b-63f1-4649-64b8-655955f295cd-5151/


Sorry for the confusion. Hopefully this hasn't caused too much headache on your end. If there are further questions, let me know.



________________________________
