### ISSUE TITLE
Filters to update tissue browser and stage.

### ISSUE THREAD

**Issue by adphillips2017** [hubmapconsortium/ccf-ui#171]
From issue #143 

- [x] Closing the Filter Flyout on click of the Apply Filters button
    - [x] updating the list in the Tissue Browser to reflect the applied filters, this includes changing the values of the text area at the top of the TB and the list of available items below, a spinner will appear while the data is updating (NOTE: top text should appear first, the list only when complete. Animate both in with a fade, ease in-out.)

- [x] Update the text in the right drawer to reflect the new Sex, Age, BMI values
- [x] Update Stage with the correct body type based on Sex

**Comment by bherr2** [comment]
@lecross where should the spinner appear? In the middle of the stage, replacing the filter button temporrarily, on the apply filters button, somewhere else? Does it stop the filter popup from closing?

**Comment by bherr2** [comment]
For the accurate display of "downloading/querying" state, each component says when they are querying data and when they are done. When all things are done querying, remove spinner.

**Comment by lecross** [comment]
Bruce,


The spinner should be center. Since the action is to click the apply button in the filters area, the spinner is predicated on that action. The filter flyout should close. The overlay appears, then the spinner. Both items should fade on and off the stage. When the content is updated, the reverse order should happen. First the spinner fades out, then the overlay. Timing for the fade animation for each item should be 0.3-0.6. Since the spinner is smaller, a short fade time is probably better. The larger overlay should take longer. Potentially, the total time for the entire animation sequence is about a second. If this feels too long, then do what feels best. I am not a fan of everything abruptly disappearing all at once or too quickly. Rapid movement is disruptive.


Use ease-in-out. Easing should not be linear.


Let me know if any part of that doesn't make sense or there are questions.



________________________________
