### ISSUE TITLE
As a <researcher>, I want <to see an about page> so that <I can learn about the project>

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#21]
Acceptance Criteria:

* [ ] at the very top right of the screen an information icon button is visible
* [ ] on click, a modal/popup displays a page with about information
* [ ] on click of the close button or in the blurred region, the modal shall close

Notes:
* @lecross will provide the help/about text/html to embed in the model/popup (see Page 6)

**Comment by gurjaspalbedi** [comment]
@lecross @bherr2 I need information regarding the links on this about page. The links are highlighted in yellow.

![image.png](https://images.zenhubusercontent.com/5b9290b9fb5dec0b0d9cb85b/49dd76c6-c18f-41e5-8ea5-35a4a0590372)

**Comment by lecross** [comment]
Jassi,

There is the potential these will change. But use these for now.


HuBMAP
The Human Biomolecular Atlas Project (HuBMAP) will develop the next generation of molecular analysis technologies, computational tools, and to generate foundational tissue maps in order to accelerate the construction of an atlas of the human body for the understanding the relationship between tissue organization and function.
https://hubmapconsortium.org

Common Coordinate Framework (CCF)
The HuBMAP common coordinate (reference) framework is under active development. It aims to spatially annotate and index HuBMAP data so this data can be spatially located and explored efficiently. The CCF v0.5.0 became available in March 2019. CCF Ontology documentation is available here<https://docs.google.com/document/d/1X21O5DgGkq9ngPOsBZa-qy1-6Y2MiohJD7Bt-JFyysY/edit> and OWL file is available on GitHub<https://github.com/hubmapconsortium/hubmap-ontology>.

CCF User Interface (UI)
The CCF UI represents data across multiple scales, supporting navigation by multiple coordinate systems, including spatial, physiologic, and organ-based browsing.  This proof-of-concept user interface for the CCF v0.5.0 became available in June 2019 and will evolve as more data becomes available. CCF UI specification is available *here* and code is available on GitHub.   <- link to final spec/code

Acknowledgements
The CCF work was completed by Katy Börner, Bruce Herr II, Paul Macklin, Randy Heiland & Ellen Quardokus, Indiana University, Bloomington, IN; Griffin Weber, Harvard Medical School, Boston, MA; and Samuel Friedman, Opto-Knowledge Systems, Inc. with expert input by the HuBMAP team. Data was provided by the Tissue Mapping Center (TMC) at Vanderbilt University. The work was funded by NIH Award OT2OD026671<https://projectreporter.nih.gov/project_info_description.cfm?aid=9687220>.

**Comment by lecross** [comment]
![image.png](https://images.zenhubusercontent.com/5c128369c26aad40d124f4ec/5a3fa045-626b-48ff-884b-9a3dc0bad362)

**Comment by gurjaspalbedi** [comment]
@lecross Hi Leonard we do not have subtitle in the text provided but in image we have subtitle. So what should I follow?

**Comment by bherr2** [comment]
Please adjust the top spacing between the subtitle and the text and the spacing between the NIH logo and the bottom of the text.

**Comment by bherr2** [comment]
Also, add in the missing links in the text. Let me know if you don't know where those are.

**Comment by gurjaspalbedi** [comment]
Hi @bherr2, In CCF User Interface (UI) paragraph I need two links in the text "CCF UI specification is available here and code is available on GitHub."

For GitHub, I will be using - https://github.com/hubmapconsortium/ccf-ui
I want link for 'here', that is the link to the specification that should be shared.

**Comment by bherr2** [comment]
Looks good. One minor change: all links on about page should have target="_blank" (ie open in new window).

**Comment by bherr2** [comment]
I went ahead and put that in for you. This task is now done done. :-)
