### ISSUE TITLE
Default view in Register mode too close

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#427]
When I load the RUI on my 4K display, the camera seems to be way too close to the organ to work properly, see below. Since the camera in Register mode cannot be zoomed in and out, this presents a problem:
![image](https://user-images.githubusercontent.com/22821046/99713549-74d9c800-2a72-11eb-9801-62679c437adc.png)

No issue on my 1080p display:
![image](https://user-images.githubusercontent.com/22821046/99713604-8622d480-2a72-11eb-829e-633d4c96ead7.png)

**Comment by bherr2** [comment]
After talking with Andreas, it appears part of the issue here is that some HiDPI/Retina displays have a higher pixel ratio. We can use [`window.devicePixelRatio`](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) to account for this when doing the zoom to bounding box feature.

**Comment by bherr2** [comment]
Fixed in `develop`
