### ISSUE TITLE
Use dataset thumbnails from Elastic search

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ccf-ui#624]
Once the IEC has implemented this feature (track progress [here](https://github.com/orgs/hubmapconsortium/projects/3?card_filter_query=milestone%3A%22eui+thumbnails%22)), update the logic in hubmap-data.ts to check for the existence of dataset thumbnails (@shirey , we will need some documentation and notification once its ready) and create thumbnail links from it.

We will leave the existing thumbnail logic in as a backup until a later date when we remove it in favor of this new method.

**Comment by yuanzhou** [comment]
The thumbnail images of the following 40 Datasets have been registered and available on TEST:

`['ceff8dd907f28fd1508f4f4201d851d2', '3333fdaa86c242b2d6fb33f6b66befb3', '187ec1fd772164bc8b6a8ea6dbf770ae', 'b7a2c05fdd9ddd0c83c9786ede98a24e', 'aedc30c204870180673b6ece299f2eb1', 'cc28d4b6954608bd6d045f98728ffb6b', '1eadf62812799712d4b1232cc92b132f', 'cd25af3631d76c34691062d5a2b54e1a', 'c95ebd4e7589993db7884a48cb2b3114', '5723910250c696b6c682fe8137870832', 'd0b944edce4f7fc2a61321d5dc915a72', '0ca61e7926956da9b8bdde2b1f3c43af', '5409cced402ef1eec2d5eca8912bfbee', '75edcda4f3ff5bef72383d5d082438c2', '8d8df70aa94be7f65283d7f3cdc05553', 'd8d17995448d651e003abfbb0e0f7c62', '2c3540e2b1040c06612698d80ecab56a', '4c0479bd703d8be3c2834dd1b6773b4c', '85b4a45353628c7ab7326f9491dc3ef4', 'f4cdcc39efdb068f91c29dc53f1504c9', '2dc0514607ae08af7004d9cb8c9640c9', 'b86ca8d3370798d10e203ac7f8090e3e', '25af9808426a36f87cd3450b8eb83684', '2130d5f91ce61d7157a42c0497b06de8', 'f31451771e1e2ceb31f8ac625a6fcca2', 'd36df353338a4a450f2282c65218f16c', 'd4017eaa2282a9d193aad75ec491498b', '23f1637a0a90fdd2a8feece44d00c22e', '0bf9cb40adebcfb261dfbe9244607508', '65dffa77af3430412ceb873e27660d40', '4a4c3947a7590031d1ff405557354fdb', '03043e079260d180099579045f16cd53', '23f3245f31fcbd011b3efc0bc5f98fc4', 'd3f2eaa0d0d56e143d6700fde6ca71f3', 'e0ba24d0c4dab528e46aab3f67a1aae8', 'e4ddfd3408f7a7baaad1cebdd5ab7d4b', 'f4188a148e4c759092d19369d310883b', 'a698201644fede089d32d57b1e592753', '8f528475e216c283851e6941841d7173', '4a1f8f0e22cf184574896ee1005c01c7']`

To query one of them from Elasticsearch via search-api:
````
GET /search HTTP/1.1
Host: search-api.test.hubmapconsortium.org
Content-Type: application/json

{
  "query": {
    "match": {
      "uuid": "4a1f8f0e22cf184574896ee1005c01c7"
    }
  }
}
````

You'll find the thumbnail file info at `hits.hits[0]._source.thumbnail_file`:
````
"thumbnail_file": {
    "file_uuid": "c35002f9c3d49f8b77e1e2cd4a01803d",
    "filename": "thumbnail.jpg"
}
````
All the registered thumbnail images are using this same `thumbnail.jpg` filename.

Then make another call to download the image via assets file service. The file path pattern: `<file_uuid>/thumbnail.jpg`

````
GET /c35002f9c3d49f8b77e1e2cd4a01803d/thumbnail.jpg HTTP/1.1
Host: assets.test.hubmapconsortium.org
````

Since these thumbnail files are registered with the published Datasets, no token is required for the above calls. If by any chance the Dataset with the thumbnail file is not published, add the globus nexus token in the `Authorization` header like below:
````
Authorization: Bearer Ag8ryKmQv5wmoYDDew8Kbg30xGrrlQW12dgy0bbm7BOeN2d4GvS8C2p8Na9v2WJkpDzM0GmVJq7KvMs727ea5Ix0G4
````

**Comment by yuanzhou** [comment]
FYI @bherr2 and @shirey : all the above 40 EUI thumbnails have been registered on PROD
