### ISSUE TITLE
Entry Modal - Start Registration

### ISSUE THREAD

**Issue by andreasbueckle** [hubmapconsortium/ccf-ui#745]
When presenting the user with modal upon opening an instance of the **standalone** RUI, we should capture their ORCID. This might have to be implemented inside a larger strategy for user profiles as it might be unrealistic to expect a user to type in their ORCID every time. Perhaps a login via ORCID could be doable, too.

**Comment by bherr2** [comment]
Login via ORCID is not a possibility for Y4. We could add ORCID as an (optional, I assume) field in addition to First Name, Last Name and use localStorage to prefill the form each time if they are using the same browser. 

Additionally, if IEC (CC @shirey) has ORCIDs associated with users we might be able to prefill this in the ingest portal as well.

**Comment by andreasbueckle** [comment]
@katyb Re: your request to add capture users' ORCIDs.

**Comment by bherr2** [comment]
I think this feature has to wait until we have a systematic way of getting (or having them provided) users orcids during the ingest/rui registration process.

**Comment by libby-maier** [comment]
# Entry Modal - Start Registration

## Old Entry Modal
![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/414f6bb5-0a1d-4ab6-952f-a2d82e364bab)

## New Entry Modal
![image](https://github.com/hubmapconsortium/ccf-ui/assets/97060856/1653422c-efad-4322-8b49-b4b0d1742f20)


## Design notes for Entry Modal
### View the [Figma Design File: Entry Modal](https://www.figma.com/file/KMti4IJGUUQrle2rl1n2Go/RUI?type=design&node-id=678-431&mode=design&t=PhMlvOm1lUoGC8KU-4)

### UX/UI Notes
- Please keep the same functionality of the modal popping up as soon as the user enters the RUI. The modal needs to be centered and there needs to be a background as there currently is in the RUI.
- Please use all of the same text input fields in the current interface for this modal. All of the input field states will stay the same as well.
- Use the EUI's Spatial Search Dropdown component for the new select an organ dropdown. It should look/feel exactly the same. There might be a slight difference from Figma, and that is okay as long as the "select an organ" dropdown code is recycled from the EUI.
- Required fields: First name, last name, donor sex, select an organ.
- The continue button is disabled until all required fields are filled out. It shifts to the ready state when this is completed.
- Please contact me with any questions, per usual!

### User Stories
- As a user, I need to have an author data section to record my information, so that the HuBMAP consortium can track registration data accurately.
- As a user, I want an optional input for my ORCID, so that this can be displayed in HuBMAP datasets eventually.
- As a user, I need a donor data section, so that my registration data is accurately recorded for the HuBMAP consortium.
- As a user, I need radio buttons for multiple choice options, so that I don't have to guess about the direction of a toggle switch.
- As a user, I need an alphabetical listing of organs available for registration, so that I select the correct organ for my registration.
- As a user, I need an area to upload my previous registration data JSON files, so that I can see previously registered blocks in the interface.
- As a user, I need the upload previous registration data section to show if files are uploaded, so that I know that I have the correct file.

**Comment by bherr2** [comment]
@jsaikiran19 probably makes sense to let @edlu77 do this one as the right side menu is extremely similar
